import { Achievement } from "@/types/budget";

export const initializeAchievements = (): Achievement[] => [
    {
        id: "streak_3",
        title: "Getting Started",
        description: "Log in for 3 consecutive days",
        type: "login_streak",
        target: 3,
        current: 0,
        isUnlocked: false,
        icon: "🔥",
    },
    {
        id: "streak_5",
        title: "Consistent Tracker",
        description: "Log in for 5 consecutive days",
        type: "login_streak",
        target: 5,
        current: 0,
        isUnlocked: false,
        icon: "⭐",
    },
    {
        id: "streak_7",
        title: "Weekly Warrior",
        description: "Log in for 7 consecutive days",
        type: "login_streak",
        target: 7,
        current: 0,
        isUnlocked: false,
        icon: "🏆",
    },
    {
        id: "streak_14",
        title: "Fortnight Fighter",
        description: "Log in for 14 consecutive days",
        type: "login_streak",
        target: 14,
        current: 0,
        isUnlocked: false,
        icon: "💎",
    },
    {
        id: "streak_30",
        title: "Monthly Master",
        description: "Log in for 30 consecutive days",
        type: "login_streak",
        target: 30,
        current: 0,
        isUnlocked: false,
        icon: "👑",
    },
    {
        id: "first_save",
        title: "First Saver",
        description: "Save your first $100",
        type: "savings",
        target: 100,
        current: 0,
        isUnlocked: false,
        icon: "💰",
    },
    {
        id: "budget_keeper",
        title: "Budget Keeper",
        description: "Stay under budget for a month",
        type: "spending",
        target: 1,
        current: 0,
        isUnlocked: false,
        icon: "📊",
    },
];
